package lv.boardgame.bot.mybot;

public enum BotState {
	START,
	WAITING_DATE,
	WAITING_TIME,
	WAITING_PLACE,
	WAITING_GAME_NAME,
	WAITING_MAX_PLAYER_COUNT,
	WAITING_IF_ORGANIZER_PLAYING,
	WAITING_COMMENT
}
